name: Pipeline 3 - Despliegue a ACI

on:
  workflow_dispatch:

env:
  RESOURCE_GROUP: "rg-prestamos"
  ACR_NAME: "acrprestamos2026"
  APP_PORT: 8080
  CONTAINER_NAME: "simulador-app"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout código
        uses: actions/checkout@v4


      - name: Login a Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3


      - name: Terraform Init
        working-directory: terraform
        run: terraform init


      - name: Importar recursos existentes
        working-directory: terraform
        run: |

          terraform import azurerm_resource_group.rg \
          /subscriptions/87663e4a-5ca0-4144-927f-a0ba95bd7322/resourceGroups/rg-prestamos || true


          terraform import azurerm_container_registry.acr \
          /subscriptions/87663e4a-5ca0-4144-927f-a0ba95bd7322/resourceGroups/rg-prestamos/providers/Microsoft.ContainerRegistry/registries/acrprestamos2026 || true


          terraform import azurerm_cosmosdb_account.db \
          /subscriptions/87663e4a-5ca0-4144-927f-a0ba95bd7322/resourceGroups/rg-prestamos/providers/Microsoft.DocumentDB/databaseAccounts/prestamos-cosmos-dev || true


          terraform import azurerm_virtual_network.vnet \
          /subscriptions/87663e4a-5ca0-4144-927f-a0ba95bd7322/resourceGroups/rg-prestamos/providers/Microsoft.Network/virtualNetworks/vnet-prestamos || true


          terraform import azurerm_subnet.subnet \
          /subscriptions/87663e4a-5ca0-4144-927f-a0ba95bd7322/resourceGroups/rg-prestamos/providers/Microsoft.Network/virtualNetworks/vnet-prestamos/subnets/subnet-prestamos || true



      - name: Crear infraestructura faltante
        working-directory: terraform
        run: terraform apply -auto-approve



      - name: Obtener información del ACI
        run: |

          ACI_NAME=$(az container list \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --query "[?contains(name, 'prestamos-aci')].name" \
          --output tsv)


          if [ -z "$ACI_NAME" ]; then
            echo "No se encontró el ACI"
            exit 1
          fi


          echo "ACI_NAME=$ACI_NAME" >> $GITHUB_ENV
          echo "ACI encontrado: $ACI_NAME"



      - name: Obtener IP del ACI
        run: |

          IP_ADDRESS=$(az container show \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --name ${{ env.ACI_NAME }} \
          --query "ipAddress.ip" \
          --output tsv)


          echo "CONTAINER_IP=$IP_ADDRESS" >> $GITHUB_ENV

          echo "IP del ACI: $IP_ADDRESS"



      - name: Validar contenedor
        run: |

          STATE=$(az container show \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --name ${{ env.ACI_NAME }} \
          --query "containers[0].instanceView.currentState.state" \
          --output tsv)


          echo "Estado del contenedor: $STATE"


          if [ "$STATE" != "Running" ]; then

            echo "El contenedor no está ejecutándose"

            az container logs \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.ACI_NAME }} \
            --container-name ${{ env.CONTAINER_NAME }}

            exit 1

          fi


      - name: Resumen final
        run: |

          echo "================================="
          echo "DESPLIEGUE COMPLETADO"
          echo "================================="
          echo "ACI: ${{ env.ACI_NAME }}"
          echo "IP: ${{ env.CONTAINER_IP }}"
          echo "Puerto: ${{ env.APP_PORT }}"
          echo "================================="
