name: Pipeline 3 - Despliegue a ACI

on:
  workflow_dispatch:

env:
  RESOURCE_GROUP: "rg-prestamos"
  ACR_NAME: "acrprestamos2026"
  APP_PORT: 8080
  CONTAINER_NAME: "simulador-app"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout código
        uses: actions/checkout@v4

      - name: Login a Azure con credenciales
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Crear ACI con Terraform
        run: terraform apply -auto-approve

      - name: Obtener información del ACR
        run: |
          ACR_LOGIN_SERVER=$(az acr show \
            --name ${{ env.ACR_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --query loginServer \
            --output tsv)

          echo "ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER" >> $GITHUB_ENV
          echo "ACR encontrado: $ACR_LOGIN_SERVER"

      - name: Obtener el nombre del ACI
        run: |
          ACI_NAME=$(az container list \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --query "[?contains(name, 'prestamos-aci')].name" \
            --output tsv)

          if [ -z "$ACI_NAME" ]; then
            echo "No se encontró el ACI"
            exit 1
          fi

          echo "ACI_NAME=$ACI_NAME" >> $GITHUB_ENV
          echo "ACI encontrado: $ACI_NAME"

      - name: Obtener imagen del ACR
        run: |
          IMAGE_TAG=$(az acr repository show-tags \
            --name ${{ env.ACR_NAME }} \
            --repository ${{ env.CONTAINER_NAME }} \
            --orderby time_desc \
            --top 1 \
            --output tsv)

          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

          echo "Imagen:"
          echo "${{ env.ACR_NAME }}.azurecr.io/${{ env.CONTAINER_NAME }}:$IMAGE_TAG"

      - name: Reiniciar contenedor
        run: |
          az container restart \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.ACI_NAME }} \
            --container-name ${{ env.CONTAINER_NAME }}

      - name: Esperar contenedor activo
        run: |
          MAX_ATTEMPTS=30
          ATTEMPT=0
          STATE="Unknown"

          while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do

            STATE=$(az container show \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --name ${{ env.ACI_NAME }} \
              --query "containers[0].instanceView.currentState.state" \
              --output tsv)

            echo "Estado: $STATE"

            if [ "$STATE" = "Running" ]; then
              echo "Contenedor ejecutándose"
              break
            fi

            sleep 10
            ATTEMPT=$((ATTEMPT+1))

          done

          if [ "$STATE" != "Running" ]; then
            echo "El contenedor no inició"
            exit 1
          fi

      - name: Obtener IP del contenedor
        run: |
          IP_ADDRESS=$(az container show \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.ACI_NAME }} \
            --query "ipAddress.ip" \
            --output tsv)

          echo "CONTAINER_IP=$IP_ADDRESS" >> $GITHUB_ENV

          echo "IP:"
          echo "$IP_ADDRESS"

      - name: Validar aplicación
        run: |
          APP_URL="http://${{ env.CONTAINER_IP }}:${{ env.APP_PORT }}"

          echo "Probando:"
          echo "$APP_URL"

          HTTP_CODE=$(curl -s \
            -o /dev/null \
            -w "%{http_code}" \
            --connect-timeout 10 \
            --max-time 15 \
            "$APP_URL/health" || echo "000")

          if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "404" ]; then
            echo "Aplicación responde correctamente"
          else
            echo "Aplicación no responde"
            
            az container logs \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --name ${{ env.ACI_NAME }} \
              --container-name ${{ env.CONTAINER_NAME }}

            exit 1
          fi

      - name: Mostrar resumen
        run: |
          echo "================================="
          echo "DESPLIEGUE COMPLETADO"
          echo "================================="
          echo "Contenedor: ${{ env.ACI_NAME }}"
          echo "Imagen: ${{ env.ACR_NAME }}.azurecr.io/${{ env.CONTAINER_NAME }}:${{ env.IMAGE_TAG }}"
          echo "URL: http://${{ env.CONTAINER_IP }}:${{ env.APP_PORT }}"
          echo "================================="
