name: Pipeline 3 - Despliegue a ACI y AppGW

on:
  workflow_dispatch:

env:
  RESOURCE_GROUP: "rg-prestamos"
  ACR_NAME: "acrprestamos2026"
  APP_PORT: 8080
  CONTAINER_NAME: "simulador-app"
  SUBSCRIPTION_ID: "87663e4a-5ca0-4144-927f-a0ba95bd7322"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout código
        uses: actions/checkout@v4


      - name: Login Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      - name: Verificar suscripción Azure
        run: |
          az account show


      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3


      - name: Terraform Init
        working-directory: terraform
        run: terraform init


      - name: Importar recursos existentes
        working-directory: terraform
        run: |

          terraform import azurerm_resource_group.rg \
          /subscriptions/${{ env.SUBSCRIPTION_ID }}/resourceGroups/${{ env.RESOURCE_GROUP }} || true

          terraform import azurerm_container_registry.acr \
          /subscriptions/${{ env.SUBSCRIPTION_ID }}/resourceGroups/${{ env.RESOURCE_GROUP }}/providers/Microsoft.ContainerRegistry/registries/${{ env.ACR_NAME }} || true

          terraform import azurerm_cosmosdb_account.db \
          /subscriptions/${{ env.SUBSCRIPTION_ID }}/resourceGroups/${{ env.RESOURCE_GROUP }}/providers/Microsoft.DocumentDB/databaseAccounts/prestamos-cosmos-dev || true

          terraform import azurerm_virtual_network.vnet \
          /subscriptions/${{ env.SUBSCRIPTION_ID }}/resourceGroups/${{ env.RESOURCE_GROUP }}/providers/Microsoft.Network/virtualNetworks/vnet-prestamos || true

          terraform import azurerm_subnet.subnet \
          /subscriptions/${{ env.SUBSCRIPTION_ID }}/resourceGroups/${{ env.RESOURCE_GROUP }}/providers/Microsoft.Network/virtualNetworks/vnet-prestamos/subnets/subnet-prestamos || true


      - name: Mostrar recursos Terraform
        working-directory: terraform
        run: terraform state list


      - name: Desplegar ACI
        working-directory: terraform
        run: |
          terraform apply \
          -target=azurerm_container_group.aci \
          -auto-approve


      - name: Buscar ACI creado
        run: |

          ACI_NAME=$(az container list \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --query "[].name" \
          --output tsv)

          if [ -z "$ACI_NAME" ]; then
            echo "No existe ningún ACI en el Resource Group"
            exit 1
          fi

          echo "ACI_NAME=$ACI_NAME" >> $GITHUB_ENV
          echo "ACI encontrado: $ACI_NAME"


      - name: Ver estado del contenedor
        run: |

          STATE=$(az container show \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --name ${{ env.ACI_NAME }} \
          --query "containers[0].instanceView.currentState.state" \
          --output tsv)

          echo "Estado del contenedor: $STATE"


      - name: Obtener IP Pública y Dominio
        run: |
          
          # Obtener IP pública del ACI
          IP=$(az container show \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --name ${{ env.ACI_NAME }} \
          --query "ipAddress.ip" \
          --output tsv)

          # Obtener FQDN (Nombre de dominio) del ACI
          FQDN=$(az container show \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --name ${{ env.ACI_NAME }} \
          --query "ipAddress.fqdn" \
          --output tsv)

          echo "CONTAINER_IP=$IP" >> $GITHUB_ENV
          echo "CONTAINER_FQDN=$FQDN" >> $GITHUB_ENV

          echo "IP Pública ACI: $IP"
          echo "URL: $FQDN"


      - name: Resumen final
        run: |

          echo "================================="
          echo "DESPLIEGUE FINALIZADO"
          echo "================================="
          echo "ACI: ${{ env.ACI_NAME }}"
          echo "---------------------------------"
          echo "🌐 ACCESO PÚBLICO: http://${{ env.CONTAINER_FQDN }}:${{ env.APP_PORT }}"
          echo "IP Pública: ${{ env.CONTAINER_IP }}"
          echo "================================="